name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Runs when pushing to the 'main' branch

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Fetch latest code from GitHub

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Dependencies
        run: npm install  # Install all project dependencies

      - name: Build Project
        run: npm run build  # Generate the production build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages  # Deploy to gh-pages branch
          folder: dist       # The folder that gets deployed
